/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    'fee-structures': FeeStructure;
    articles: Article;
    placements: Placement;
    'placement-hero': PlacementHero;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'fee-structures': FeeStructuresSelect<false> | FeeStructuresSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    placements: PlacementsSelect<false> | PlacementsSelect<true>;
    'placement-hero': PlacementHeroSelect<false> | PlacementHeroSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  title: string;
  /**
   * URL path, e.g. bba/business-analytics
   */
  slug: string;
  /**
   * e.g. "BBA", "BTech", "MBA"
   */
  program?: string | null;
  /**
   * e.g. "School of Management"
   */
  school?: string | null;
  status?: ('draft' | 'published') | null;
  sections?:
    | (
        | {
            breadcrumb: {
              currentRoute: string;
            };
            badge?: string | null;
            title: string;
            highlight?: string | null;
            description: string;
            /**
             * Full-bleed hero background photo, rendered under the existing gradient tint. Takes priority over the upload field below. Leave both empty for gradient-only (current default look).
             */
            image?: string | null;
            /**
             * Upload a hero background photo — only used if the Background image URL above is empty.
             */
            photo?: (string | null) | Media;
            chips?:
              | {
                  strong?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            buttons?:
              | {
                  /**
                   * Must match a variant the Button component actually supports.
                   */
                  variant?:
                    | (
                        | 'orange'
                        | 'orange_b'
                        | 'orange_anim'
                        | 'white_outline'
                        | 'white_outline_b2'
                        | 'white_outline_anim'
                        | 'black_anim'
                      )
                    | null;
                  /**
                   * e.g. "IoCall" — must match an icon name the component recognizes
                   */
                  icon?: string | null;
                  label: string;
                  /**
                   * e.g. "/apply-now" or "https://tulas.edu.in/contact". Leave empty for a non-functional button.
                   */
                  url?: string | null;
                  openInNewTab?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            imageCard?: {
              changeDesign?: number | null;
              title?: string | null;
              /**
               * Use line breaks for multi-line highlight text
               */
              highlight?: string | null;
              /**
               * Photo shown in this card. Takes priority over the upload field below. Leave both empty and the card shows without a photo.
               */
              imageUrl?: string | null;
              /**
               * Optional photo upload — only used if the Photo URL above is empty.
               */
              image?: (string | null) | Media;
            };
            header?: {
              label?: string | null;
              title?: string | null;
              highlight?: string | null;
            };
            description1?: string | null;
            description2?: string | null;
            quote?: string | null;
            table?: {
              headers?: string[] | null;
              rows?:
                | {
                    program: string;
                    duration?: string | null;
                    eligibility?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'overview';
          }
        | {
            header?: {
              label?: string | null;
              title?: string | null;
              highlight?: string | null;
              para?: string | null;
            };
            cards?:
              | {
                  title: string;
                  desc?: string | null;
                  pills?: string[] | null;
                  id?: string | null;
                }[]
              | null;
            extraCard?: {
              /**
               * Use line breaks for multi-line title
               */
              title?: string | null;
              description?: string | null;
            };
            coreTags?: string[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'coursesGrid';
          }
        | {
            image?: {
              /**
               * Multi-line placeholder text shown inside the visual block (used only if no photo URL/upload is set below)
               */
              placeholder?: string | null;
              /**
               * Real photo — if set, replaces the placeholder box with this image. Takes priority over the upload field below.
               */
              url?: string | null;
              alt?: string | null;
              /**
               * Optional real photo upload — only used if the Photo URL above is empty
               */
              photo?: (string | null) | Media;
            };
            header?: {
              label?: string | null;
              title?: string | null;
              highlight?: string | null;
              para?: string | null;
            };
            tags?: string[] | null;
            roadmap?:
              | {
                  num: string;
                  title: string;
                  desc?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aiSection';
          }
        | {
            header?: {
              label?: string | null;
              title?: string | null;
              highlight?: string | null;
              para?: string | null;
            };
            certificationAssociations?:
              | {
                  isMain?: boolean | null;
                  badge?: string | null;
                  name: string;
                  desc?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Currently rendered as plain strings — flag with your dev if these should support icons/images later.
             */
            handsOnItems?: string[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'certifications';
          }
        | {
            badge?: string | null;
            title?: string | null;
            highlight?: string | null;
            tabs?:
              | {
                  /**
                   * Unique key, must match a "contents" entry's Tab ID below
                   */
                  id: string;
                  num?: string | null;
                  label: string;
                }[]
              | null;
            contents?:
              | {
                  /**
                   * Must match one of the tab IDs above
                   */
                  tabId: string;
                  type: 'bullet' | 'bulletWithLabels' | 'table';
                  bulletItems?: string[] | null;
                  labeledItems?:
                    | {
                        label: string;
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  tableHeaders?: string[] | null;
                  tableRows?:
                    | {
                        cells?: string[] | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programDetails';
          }
        | {
            header?: {
              label?: string | null;
              title?: string | null;
              highlight?: string | null;
              para?: string | null;
            };
            jobs?:
              | {
                  title: string;
                  /**
                   * e.g. salary range
                   */
                  range?: string | null;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  gradient?: boolean | null;
                  number: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'careers';
          }
        | {
            header?: {
              label?: string | null;
              title?: string | null;
              highlight?: string | null;
              para?: string | null;
            };
            items?:
              | {
                  n?: string | null;
                  title: string;
                  desc?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyStudy';
          }
        | {
            title?: string | null;
            highlight?: string | null;
            subtitle?: string | null;
            logos1?: string[] | null;
            logos2?: string[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'recruiters';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Fee tables shown on the /tulas-programs catalog page. The "Key" field must exactly match a feesKey in programs-data.js for it to connect to the right program.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fee-structures".
 */
export interface FeeStructure {
  id: string;
  /**
   * Must exactly match a feesKey in tulas_rev/src/lib/data/programs-data.js, e.g. "BBA" or "MBA-Specialization".
   */
  key: string;
  /**
   * Friendly name shown in this admin list, e.g. "BBA (General)".
   */
  label: string;
  /**
   * e.g. "Per annum · Scholarship based on 12th aggregate %"
   */
  note?: string | null;
  /**
   * Turn on for programs like Integrated Law / LL.B that have one fixed fee instead of scholarship brackets.
   */
  flat?: boolean | null;
  flatRows?:
    | {
        prog: string;
        fee: number;
        id?: string | null;
      }[]
    | null;
  tieredRows?:
    | {
        prog: string;
        allIndia: {
          noScholarship: number;
          s91: number;
          s81: number;
          s71: number;
          s60: number;
        };
        uttarakhand: {
          noScholarship: number;
          s91: number;
          s81: number;
          s71: number;
          s60: number;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * News articles for the /media page. At most one article should be set to each Hero Position (Large / Small 1 / Small 2) at a time — the rest should be "None" and will show in the regular feed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  /**
   * URL path, e.g. "pinaak-2026-cultural-fest" — used as /media/<slug>
   */
  slug: string;
  /**
   * e.g. "DBUU Events", "Awards", "Academics"
   */
  category?: string | null;
  author?: string | null;
  publishedDate: string;
  /**
   * Manual, not auto-calculated — e.g. "4 min read". Leave empty to hide.
   */
  readTime?: string | null;
  /**
   * Takes priority over the upload field below. Leave both empty and the card shows without a photo.
   */
  imageUrl?: string | null;
  /**
   * Only used if the Photo URL above is empty.
   */
  image?: (string | null) | Media;
  /**
   * Short summary shown on article cards and at the top of the article.
   */
  excerpt: string;
  /**
   * Full article content.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Photos of newspaper clippings / press coverage for this story — shown as a slider on the article page. Leave empty to hide the gallery entirely.
   */
  newspaperGallery?:
    | {
        /**
         * Takes priority over the upload field below.
         */
        imageUrl?: string | null;
        /**
         * Only used if the Photo URL above is empty.
         */
        image?: (string | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Other sites that republished or covered this same story (e.g. NDTV, Times of India) — shown as "More from DevBhoomi Times" cards on this article's page. Scoped to this article only, not shared site-wide.
   */
  externalCoverage?:
    | {
        /**
         * e.g. "NDTV" or the external headline used there.
         */
        title: string;
        /**
         * Takes priority over the upload field below.
         */
        imageUrl?: string | null;
        /**
         * Only used if the Photo URL above is empty. Falls back to this article's own photo if both are empty.
         */
        image?: (string | null) | Media;
        link: string;
        linkLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Only one published article at a time can hold each hero position — enforced automatically.
   */
  heroPosition?: ('none' | 'large' | 'small-1' | 'small-2') | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One record per placed student. Shown in the course sections on /placement and the Tier 1 / Tier 2 / Popular / Normal breakdown on each course's "View All Placements" page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements".
 */
export interface Placement {
  id: string;
  studentName: string;
  /**
   * Takes priority over the upload field below.
   */
  imageUrl?: string | null;
  /**
   * Only used if the Photo URL above is empty.
   */
  image?: (string | null) | Media;
  /**
   * Which of the 9 placement course sections this student appears under.
   */
  course: 'btech-cse' | 'btech-core' | 'bba' | 'bca' | 'bcom' | 'mba' | 'bsc-agriculture' | 'bajmc' | 'mca';
  /**
   * Recruiting company, e.g. "TCS".
   */
  company: string;
  /**
   * Takes priority over the upload field below.
   */
  companyLogoUrl?: string | null;
  /**
   * Only used if the Company Logo URL above is empty.
   */
  companyLogo?: (string | null) | Media;
  /**
   * e.g. "44 LPA"
   */
  package: string;
  /**
   * e.g. "Software Dev Engineer". Optional.
   */
  designation?: string | null;
  /**
   * e.g. "Class of 2026". Optional.
   */
  batch?: string | null;
  /**
   * Tier 1 / Tier 2 / Popular each show up to 5 students on the course's inner page; Normal shows every remaining placement with no cap.
   */
  tier: 'tier-1' | 'tier-2' | 'popular' | 'normal';
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Curated spotlight cards for the sliding hero banner at the top of /placement. Independent of the Placements collection below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement-hero".
 */
export interface PlacementHero {
  id: string;
  studentName: string;
  /**
   * Takes priority over the upload field below.
   */
  imageUrl?: string | null;
  /**
   * Only used if the Photo URL above is empty.
   */
  image?: (string | null) | Media;
  /**
   * Short blurb shown on the hero card, e.g. role + a line about the achievement.
   */
  content: string;
  /**
   * e.g. "44 LPA". Optional.
   */
  package?: string | null;
  /**
   * e.g. "Software Dev Engineer". Optional.
   */
  designation?: string | null;
  /**
   * e.g. "Class of 2026". Optional.
   */
  batch?: string | null;
  /**
   * Takes priority over the upload field below.
   */
  companyLogoUrl?: string | null;
  /**
   * Only used if the Company Logo URL above is empty.
   */
  companyLogo?: (string | null) | Media;
  /**
   * Slide order, lowest first. Cards with the same number fall back to newest first.
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'fee-structures';
        value: string | FeeStructure;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'placements';
        value: string | Placement;
      } | null)
    | ({
        relationTo: 'placement-hero';
        value: string | PlacementHero;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  program?: T;
  school?: T;
  status?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              breadcrumb?:
                | T
                | {
                    currentRoute?: T;
                  };
              badge?: T;
              title?: T;
              highlight?: T;
              description?: T;
              image?: T;
              photo?: T;
              chips?:
                | T
                | {
                    strong?: T;
                    label?: T;
                    id?: T;
                  };
              buttons?:
                | T
                | {
                    variant?: T;
                    icon?: T;
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        overview?:
          | T
          | {
              imageCard?:
                | T
                | {
                    changeDesign?: T;
                    title?: T;
                    highlight?: T;
                    imageUrl?: T;
                    image?: T;
                  };
              header?:
                | T
                | {
                    label?: T;
                    title?: T;
                    highlight?: T;
                  };
              description1?: T;
              description2?: T;
              quote?: T;
              table?:
                | T
                | {
                    headers?: T;
                    rows?:
                      | T
                      | {
                          program?: T;
                          duration?: T;
                          eligibility?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        coursesGrid?:
          | T
          | {
              header?:
                | T
                | {
                    label?: T;
                    title?: T;
                    highlight?: T;
                    para?: T;
                  };
              cards?:
                | T
                | {
                    title?: T;
                    desc?: T;
                    pills?: T;
                    id?: T;
                  };
              extraCard?:
                | T
                | {
                    title?: T;
                    description?: T;
                  };
              coreTags?: T;
              id?: T;
              blockName?: T;
            };
        aiSection?:
          | T
          | {
              image?:
                | T
                | {
                    placeholder?: T;
                    url?: T;
                    alt?: T;
                    photo?: T;
                  };
              header?:
                | T
                | {
                    label?: T;
                    title?: T;
                    highlight?: T;
                    para?: T;
                  };
              tags?: T;
              roadmap?:
                | T
                | {
                    num?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        certifications?:
          | T
          | {
              header?:
                | T
                | {
                    label?: T;
                    title?: T;
                    highlight?: T;
                    para?: T;
                  };
              certificationAssociations?:
                | T
                | {
                    isMain?: T;
                    badge?: T;
                    name?: T;
                    desc?: T;
                    id?: T;
                  };
              handsOnItems?: T;
              id?: T;
              blockName?: T;
            };
        programDetails?:
          | T
          | {
              badge?: T;
              title?: T;
              highlight?: T;
              tabs?:
                | T
                | {
                    id?: T;
                    num?: T;
                    label?: T;
                  };
              contents?:
                | T
                | {
                    tabId?: T;
                    type?: T;
                    bulletItems?: T;
                    labeledItems?:
                      | T
                      | {
                          label?: T;
                          text?: T;
                          id?: T;
                        };
                    tableHeaders?: T;
                    tableRows?:
                      | T
                      | {
                          cells?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        careers?:
          | T
          | {
              header?:
                | T
                | {
                    label?: T;
                    title?: T;
                    highlight?: T;
                    para?: T;
                  };
              jobs?:
                | T
                | {
                    title?: T;
                    range?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    gradient?: T;
                    number?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyStudy?:
          | T
          | {
              header?:
                | T
                | {
                    label?: T;
                    title?: T;
                    highlight?: T;
                    para?: T;
                  };
              items?:
                | T
                | {
                    n?: T;
                    title?: T;
                    desc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        recruiters?:
          | T
          | {
              title?: T;
              highlight?: T;
              subtitle?: T;
              logos1?: T;
              logos2?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fee-structures_select".
 */
export interface FeeStructuresSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  note?: T;
  flat?: T;
  flatRows?:
    | T
    | {
        prog?: T;
        fee?: T;
        id?: T;
      };
  tieredRows?:
    | T
    | {
        prog?: T;
        allIndia?:
          | T
          | {
              noScholarship?: T;
              s91?: T;
              s81?: T;
              s71?: T;
              s60?: T;
            };
        uttarakhand?:
          | T
          | {
              noScholarship?: T;
              s91?: T;
              s81?: T;
              s71?: T;
              s60?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  author?: T;
  publishedDate?: T;
  readTime?: T;
  imageUrl?: T;
  image?: T;
  excerpt?: T;
  body?: T;
  newspaperGallery?:
    | T
    | {
        imageUrl?: T;
        image?: T;
        caption?: T;
        id?: T;
      };
  externalCoverage?:
    | T
    | {
        title?: T;
        imageUrl?: T;
        image?: T;
        link?: T;
        linkLabel?: T;
        id?: T;
      };
  heroPosition?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements_select".
 */
export interface PlacementsSelect<T extends boolean = true> {
  studentName?: T;
  imageUrl?: T;
  image?: T;
  course?: T;
  company?: T;
  companyLogoUrl?: T;
  companyLogo?: T;
  package?: T;
  designation?: T;
  batch?: T;
  tier?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement-hero_select".
 */
export interface PlacementHeroSelect<T extends boolean = true> {
  studentName?: T;
  imageUrl?: T;
  image?: T;
  content?: T;
  package?: T;
  designation?: T;
  batch?: T;
  companyLogoUrl?: T;
  companyLogo?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}